name: MonolithLib
version: '1.0'
main: top.mc506lw.rebar.MonolithLib
api-version: '1.21'
authors: [ mc506lw ]
description: 高性能巨构多方块结构前置库
depend: [Rebar]
softdepend: []

commands:
  monolith:
    description: MonolithLib 主命令
    usage: /<command> [reload|list|files|preview|construct|build|info]
    permission: monolithlib.base
    aliases: [ml]
  mltest:
    description: MonolithLib 测试命令
    usage: /<command> [list|info|validate|preview|material|stop]
    permission: monolithlib.test

permissions:
  monolithlib.base:
    description: 基础权限
    default: true
  monolithlib.admin:
    description: 管理员权限
    default: op
    children:
      monolithlib.base: true
      monolithlib.reload: true
  monolithlib.reload:
    description: 允许重新加载结构
    default: op
  monolithlib.preview:
    description: 允许使用预览功能
    default: true
  monolithlib.debug:
    description: 调试权限
    default: op
  monolithlib.test:
    description: 测试命令权限
    default: true
  monolith.easybuild:
    description: 允许使用轻松放置模式
    default: true
  monolith.printer:
    description: 允许使用自动打印模式
    default: true
